version: '3.9'

services:
  app:
    build:
      context: .
    image: storefront
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASS: ${DB_ROOT_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SMTP4DEV_PORT: ${SMTP4DEV_PORT}

  db:
    image: mysql
    restart: unless-stopped
    container_name: storefront_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - dev-db-data:/var/lib/mysql
    healthcheck:
      interval: 5s
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -P 3306 -p${DB_ROOT_PASS} | grep 'mysqld is alive' || exit 1"
        ]

  adminer:
    container_name: storefront_adminer
    image: adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - ${SMTP4DEV_UI_PORT}:80
      - ${SMTP4DEV_PORT}:25

  redis:
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redisdata:/data

  celery:
    build: .
    command: celery -A storefront worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./src:/src
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SMTP4DEV_PORT: ${SMTP4DEV_PORT}

  celery-beat:
    build: .
    command: celery -A storefront beat --loglevel=info -s /tmp/celerybeat-schedule
    depends_on:
      - redis
    volumes:
      - ./src:/src
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SMTP4DEV_PORT: ${SMTP4DEV_PORT}

  flower:
    build: .
    command: celery -A storefront flower
    depends_on:
      - app
      - redis
      - celery
    volumes:
      - ./src:/src
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://${REDIS_HOST}:${REDIS_PORT}/1
      - CELERY_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/1
      - SMTP4DEV_PORT=${SMTP4DEV_PORT}
    ports:
      - ${FLOWER_PORT}:5555

volumes:
  dev-db-data:
  redisdata:
