# Generated by Django 4.1.7 on 2023-03-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='feature_product',
            new_name='featured_product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='qantity',
            new_name='quantity',
        ),
    ]
