# Generated by Django 4.1.7 on 2023-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_feature_product_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection', options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer', options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(name='product', options={'ordering': ['title']},),
        migrations.AlterField(
            model_name='product', name='description', field=models.TextField(null=True),
        ),
    ]
